config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :authors
      resources :courses
      resources :evaluations
      resources :presentations
      resources :users

      root to: "authors#index"
  end

  resources :courses
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  resources :presentations do
    resources :evaluations
  end
  resources :authors
  resources :evaluations
  
  devise_for :users, controllers: {
  registrations: 'users/registrations'
}

  resources :users do
    member do
      put 'change_role'
    end
    collection do
      get 'new_user'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"

  # define other roots
  get 'home', to: 'static_pages#home', as: 'home'
  get 'help', to: 'static_pages#help', as: 'help'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'presentations', to: 'presentations#index', as: 'presentations_path'
  get 'evaluations', to: 'evaluations#index', as: 'evaluations_path'
  get 'users', to: 'users#index', as: 'users_path'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @all_presentations = Presentation.all
      @user_presentations = Author.where(user_id: current_user.id).map(&:presentation)
      @user_evaluations = Evaluation.where(user_id: current_user.id)

      # Get the presentations that the user has not authored.
      user_presentations_ids = @user_presentations.map(&:id)
      @other_presentations = Presentation.where.not(id: user_presentations_ids).where(course: current_user.course)

      # Get the presentations that the user has not evaluated.
      user_evaluations_ids = current_user.evaluations.map(&:presentation_id)
      @presentations_without_evaluation = Presentation.where.not(id: user_evaluations_ids).where(course: current_user.course).where.not(id: user_presentations_ids)

      @user_attribute_averages = calculate_attribute_averages(@user_presentations)
      @presentations = Presentation.all.includes(:evaluations)
      @attribute_averages = calculate_attribute_averages(@presentations)
    end
  end

  def help
  end

  def about
  end

  private

  def calculate_attribute_averages(presentations)
    averages = {}
  
    # Get the numeric attributes dynamically from the database columns
    numeric_attributes = Evaluation.columns_hash.select { |_, column| [:integer, :float].include?(column.type) }.keys
    numeric_attributes -= ['user_id', 'presentation_id', 'comments', 'id']
  
    presentations.each do |presentation|
      averages[presentation] = {}
      numeric_attributes.each do |attribute|
        averages[presentation][attribute] = presentation.evaluations.average(attribute) || 0
      end
      averages[presentation]['evaluation_count'] = presentation.evaluations.count
    end
  
    averages
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="jumbotron">
    <h1>About</h1>
    <p>
        This is the CAPE project (Comprehensive Assessment of Presentation Effectiveness). This tool is a web application meant for streamlining the process of peer and self evaluation of presentations. 
        It is meant to be used by students and teachers. The application allows instructors to create presentations and then share them with students.
        The peers can then evaluate the presentation based on a set of criteria. The application then aggregates the evaluations and presents them to the presenter and instructor. 
        The presenter can then use this information to improve their presentation skills. The application also allows teachers to create classes and mointor the enrollment of students. 
        The teachers can then view the presentations and evaluations of the students in their class. 
        
    </p>

    <h1>Team Members</h1>
    <p>
        Created by Nick Webber, Nick Cech, Ryan Tussing, Mohamed Asmali, and Steven Broaddus.


    </p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="jumbotron">
    <h1>Help</h1>
    <h2> Overview </h2>
    <p>To start, please log in or create an account. If you are an instructor creating a new course, click create class and once you put in the name of your class, you can create your instructor account.</p>
    <p> Instructors can monitor all students and delete them if something is wrong so students should imput the correct information.</p>
    <p>After logging in, you will see a dashboard filled with useful information. </p>
    <p>Students have their upcoming presentations first on their dashboard where they can view it. Next is presentations that the student still has to fill out an evaluation for. Lastly, students can see the evaluations they have given.</p>
    <p> Instructors have a similar view, just listing all the presentations in their course</p>
    <p> All users have a nav bar to control between presentations, evaluations and the class roster. These pages give more in depth information of each category.</p>
    <p>The top nav bar will always have the home page so you can always go back if you get stuck.</p>
    <h2> Giving an Evaluation </h2>
    <p>When you are ready to evaluate a presentation, click the evaluate button on the presentation. Or you can navigate to it under the 'View Presentation' button.</p>
    <p> Don't worry, you are not allowed to submit the same evaluation twice so you don't have to remember which evaluations you gave already.</p> 
    <p> You will be able to see the presentation and evaluate it based on many metrics. You will also be able to leave comments on the presentation.</p>
    <p>Evaluations are anonymous to everyone except the professor.</p>
    <h2> Creating a Presentation </h2>
    <p> If you are an instructor, you can create a presentation by clicking the 'New Presentation' button on the presentations page. </p>
    <p> You will be able to fill out the title, description, and due date of the presentation. It can be changed at any time</p>
    <p> You can also delete a presentation if you need to.</p>
    <h2> Viewing the Class Roster </h2>
    <p> You can view the class roster by clicking the 'Roster' button on the nav bar. </p>
    <p> You will be able to see all the students in your class and their information. You can also delete students or change their roles to become a TA if you need to.</p>
    <br>
    <hr>
    <p>After you are done, make sure to log out!</p>
    <p>Thank you for using our web application!</p>

    <div class="center">
        <%= image_tag("kitten.jpg", alt: "Photo of a kitty", width: "700") %>
    </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div>
    <h1 class= "text-center"><strong>Comprehensive Assessment of Presentation Effectiveness</strong></h1>
    <br>
    <% if user_signed_in? %>
        <div class="row d-flex align-items-center">
            <div class="col-md-4 border-right">
                <%if current_user.role != "Instructor"%>
                <div class="d-flex flex-row gap-3">
                    <h3>Welcome, <%= current_user.first %></h3>
                    <%= link_to 'Edit Account', edit_user_registration_path, class: "presentations-back-button presentation-button" %>
                </div>
                <%else%>
                <h3>Welcome, <%= current_user.first %></h3>
                <div class="d-flex flex-row gap-3">
                    <%= link_to 'Edit Account', edit_user_registration_path, class: "presentations-back-button presentation-button" %>
                    <%= link_to 'Delete/Edit Course', course_path(current_user.course), method: :delete, data: { confirm: 'Are you sure you want to leave this course?' }, class: 'presentation-button btn-danger' %>
                </div>
                <%end%>
            </div>

            <div class="col-md-8 d-flex flex-col justify-content-center align-items-center">
                <h1>
                    <%= current_user.course.name %>
                </h1>
            </div>
        </div>

        <hr>

        <% if current_user.role == 'Student' %>
            <h3 class="bold"><%= current_user.first %>'s Upcoming Presentations:</h3>
            <% if @user_presentations.blank? %>
                <h4 class="presentation-container">You have no upcoming presentations.</h4>
            <% else %>
                <div class="d-flex flex-col gap-3">
                    <% @user_presentations.each do |presentation| %>
                        <div class="presentation-container d-flex align-items-center">
                            <div class="col-md-11 d-flex align-items-center gap-3">
                                <h4 class="bold"><%= presentation.title %></h4>
                                <span><%= presentation.due_date %></span>
                            </div>
                            
                            <%= link_to 'View Presentation', presentation_path(presentation), class: "presentation-button view-presentation-button" %>
                        </div>
                    <% end %>
                </div>
            <% end %>

            
            <hr>

            <h3 class="bold">Presentations Without Your Evaluations:</h3>
            <% if @presentations_without_evaluation.blank? %>
                <h4 class="presentation-container">You have no presentations to evaluate</h4>
            <% else %>
                <div class="d-flex flex-col gap-3">
                    <% @presentations_without_evaluation.each do |presentation| %>
                        <div class="presentation-container d-flex align-items-center">
                            <div class="col-md-11 d-flex align-items-center gap-3">
                                <h4 class="bold"><%= presentation.title %></h4>
                                <span><%= presentation.due_date %></span>
                            </div>
                            
                            <%= link_to 'View Presentation', presentation_path(presentation), class: "presentation-button view-presentation-button" %>
                            <%= link_to 'Evaluate', new_evaluation_path(presentation_id: presentation.id), class: "presentation-button new-evaluation-button" %>
                        </div>
                    <% end %>
                </div>
                <br>
            <% end %>

            
            <hr>

            <h3 class="bold"><%= current_user.first %>'s Evaluations:</h3>
            <% if @user_evaluations.blank? %>
                <h4 class="presentation-container">You have not evaluated any presentations.</h4>
            <% else %>
                <div class="d-flex flex-col gap-3">
                    <% @user_evaluations.each do |evaluation| %>
                        <div class="presentation-container d-flex align-items-center">
                            <div class="col-md-11 d-flex align-items-center gap-3">
                                <h4 class="bold"><%= @all_presentations.find(evaluation.presentation_id).title %></h4>
                                <span>Overall Score: <%= evaluation.overall_score %></span>
                            </div>
                            
                            <%= link_to 'View Evaluation', evaluation_path(evaluation), class: "presentation-button view-presentation-button" %>
                        </div>
                    <% end %>
                </div>
            <% end %>


        <% else %>
            <h3 class="bold">Upcoming Presentations:</h3>
            <% if @other_presentations.blank? %>
                <h4 class="presentation-container">There are no other presentations.</h4>
            <% else %>
                <div class="d-flex flex-col gap-3">
                    <% @other_presentations.each do |presentation| %>
                        <div class="presentation-container d-flex align-items-center">
                            <div class="col-md-11 d-flex align-items-center gap-3">
                                <h4 class="bold"><%= presentation.title %></h4>
                                <span><%= presentation.due_date %></span>
                            </div>
                            
                            <%= link_to 'View Presentation', presentation_path(presentation), class: "presentation-button view-presentation-button" %>
                            
                        </div>
                    <% end %>
                </div>
                <br>
            <% end %>
        <% end %>
    



    <% else %>

        <div class="login_container">
            <h3 class="login_header">
                STUDENTS: Please <a class="link" href="<%= new_user_session_path %>">Sign In</a> or <a class="link" href="<%= new_user_registration_path %>">Sign Up</a> to see all upcoming presentations.
             </h3>
            <hr class="separator">
            <h3 class="log_inheader">
                INSTRUCTORS: Please <a class="link" href="<%= new_course_path %>">Add Class</a> to add a course and create an instructor account or <a class="link" href="<%= new_user_session_path %>">Sign In</a>.
            </h3>
        </div>
    <% end %>
</div>