config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :authors
      resources :courses
      resources :evaluations
      resources :presentations
      resources :users

      root to: "authors#index"
  end

  resources :courses
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  resources :presentations do
    resources :evaluations
  end
  resources :authors
  resources :evaluations
  
  devise_for :users, controllers: {
  registrations: 'users/registrations'
}

  resources :users do
    member do
      put 'change_role'
    end
    collection do
      get 'new_user'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"

  # define other roots
  get 'home', to: 'static_pages#home', as: 'home'
  get 'help', to: 'static_pages#help', as: 'help'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'presentations', to: 'presentations#index', as: 'presentations_path'
  get 'evaluations', to: 'evaluations#index', as: 'evaluations_path'
  get 'users', to: 'users#index', as: 'users_path'

end

app/models/presentation.rb
class Presentation < ApplicationRecord
  has_many :authors, dependent: :destroy
  has_many :users, through: :authors
  has_many :evaluations, dependent: :destroy
  belongs_to :course

  serialize :selected_authors, Array
end

app/controllers/admin/presentations_controller.rb
module Admin
  class PresentationsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_presentation, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /presentations or /presentations.json
  def index
    @presentations = Presentation.all

    # Get both the user's presentations and the other presentations.
    @user_presentations = Author.where(user_id: current_user.id).map(&:presentation)
    @other_presentations = Presentation.where.not(id: @user_presentations.map(&:id)).where(course: current_user.course)
    
    @authors = Author.all
  end

  # GET /presentations/1 or /presentations/1.json
  def show
    @authors = Author.all

    # Get the evaluations for the presentation.
    @evaluations = Evaluation.where(presentation_id: @presentation.id)

    # Get the average of each attribute for the presentation.
    @attribute_averages = calculate_attribute_averages([@presentation])

    # Pass in the full label for each attribute.
    @attribute_labels = {
      "clear_topic_intro" => "The introduction gave me a clear idea of the topic.",
      "clear_direction_intro" => "The introduction gave me a clear idea of the direction the presentation would take.",
      "logical_sequence" => "The presentation presented information in a logical, interesting sequence.",
      "good_summary_conclusion" => "The conclusion did a good job of summarizing the content of the presentation.",
      "enough_information" => "Enough essential information was given to allow me to effectively evaluate the topic.",
      "free_from_filler" => "The presentation was free from irrelevant or filler information.",
      "filled_time" => "The presentation filled the time allotted.",
      "easily_follow" => "I could easily follow the main points of the presentation.",
      "presenter_clear_understanding" => "The presenter had a clear understanding of the material presented.",
      "consistent_findings" => "The plans, recommendations, and/or conclusions are consistent with the findings.",
      "questions_answered" => "Presenter answers all questions with explanations and elaboration.",
      "effective_visuals" => "The visuals were effective in enhancing the message.",
      "legible_visuals" => "The visuals were legible and easy to read.",
      "proper_grammar" => "Visuals were free from grammar and formatting errors.",
      "visuals_enhance" => "The number of visual aids enhanced the presentation.",
      "appropriate_timing_visuals" => "The visuals were displayed for an appropriate time and had no annoying transition effect.",
      "clear_delivery" => "The presenter spoke clearly, was easily heard, and maintained an appropriate talking rate.",
      "effective_body_language" => "The presenter maintained a good posture and made effective use of hand and body gesture.",
      "eye_contact" => "The presenter maintained eye contact with the audience.",
      "overall_score" => "Overall Score"
    }

    authors_count = @presentation.authors.count
    @student_count = User.where(course: current_user.course, role: 'Student').count - authors_count
  end

  # GET /presentations/new
  def new
    @presentation = Presentation.new

    # Find all users that are in the same course as the current user
    @users = User.where(course_id: current_user.course)

    # Initialize selected authors to empty array
    @selected_authors = []

    Rails.logger.info "@users: #{@users.inspect}"

  end

  # GET /presentations/1/edit
  def edit
    # Find all users that are in the same course as the current user
    @users = User.where(course_id: current_user.course)

    # Find all authors for the presentation
    @selected_authors = Author.where(presentation_id: @presentation.id).pluck(:user_id)
  end

  # POST /presentations or /presentations.json
  def create
    @presentation = Presentation.new(presentation_params)

    respond_to do |format|
      if @presentation.save
        create_authors
        format.html { redirect_to presentation_url(@presentation), notice: "Presentation was successfully created." }
        format.json { render :show, status: :created, location: @presentation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1 or /presentations/1.json
  def update
    respond_to do |format|
      if @presentation.update(presentation_params)
        update_selected_authors
        format.html { redirect_to presentation_url(@presentation), notice: "Presentation was successfully updated." }
        format.json { render :show, status: :ok, location: @presentation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1 or /presentations/1.json
  def destroy
    @presentation.destroy
    
    respond_to do |format|
      format.html { redirect_to presentations_url, notice: "Presentation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def presentation_params
      params.require(:presentation).permit(:title, :course_id, :due_date, :grade, :selected_authors => [])
    end

    # Update the selected authors for a presentation.
    def update_selected_authors
      delete_authors
      create_authors
    end

    # Delete all authors for a specific presentation.
    def delete_authors
      # Get the list of authors that the user selected.
      authors_to_stay = presentation_params[:selected_authors]

      # If no authors were selected, then delete all authors for the presentation.
      if authors_to_stay.blank?
        Author.where(presentation_id: @presentation.id).destroy_all
      else
        # Delete from the authors model all authors that are not in the list of selected authors.
        Author.where(presentation_id: @presentation.id).each do |author|
          unless authors_to_stay.include? author.user_id
            author.destroy
          end
        end
      end
    end

    # Create an author for each selected user
    def create_authors
      @presentation.selected_authors.each do |user_id|
        Author.create(user_id: user_id, presentation_id: @presentation.id)
      end
    end

    def calculate_attribute_averages(presentations)
      averages = {}

      # Get the numeric attributes dynamically from the database columns
      numeric_attributes = Evaluation.columns_hash.select { |_, column| [:integer, :float].include?(column.type) }.keys
      numeric_attributes -= ['user_id', 'presentation_id', 'comments', 'id']

      presentations.each do |presentation|
        averages[presentation] = {}
        numeric_attributes.each do |attribute|
          averages[presentation][attribute] = presentation.evaluations.average(attribute) || 0
        end
        averages[presentation]['evaluation_count'] = presentation.evaluations.count
      end
    
      averages
    end
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/presentations/_form.html.erb
<%= form_with(model: presentation) do |form| %>
  <% if presentation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(presentation.errors.count, "error") %> prohibited this presentation from being saved:</h2>

      <ul>
        <% presentation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class = "form-options">
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, required: true %>*
  </div>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.hidden_field :course_id, value: current_user.course_id %>
    <%= form.text_field :course_name, value: current_user.course.name, readonly: true%>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date, required: true %>*
  </div>

  <div>
    <%= form.label :grade, style: "display: block" %>
    <%= form.number_field :grade, required: false %>
  </div>

  <div>
    <%= form.label :selected_authors, style: "display: block" %>
    <% @users.each do |user| %>
      <div>
        <% if user.role == 'Student' %>
          <%= check_box_tag 'presentation[selected_authors][]', user.id, @selected_authors.include?(user.id), { multiple: true } %>
          <%= form.label "user_#{user.id}", user.first + " " + user.last %>
        <%end%>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
</div> 
<% end %>

app/views/presentations/_presentation.html.erb
<% provide(:title, "Presentations") %>
<div id="<%= dom_id presentation %>">
  <div class="presentation-container">
    <h4 class="bold"><%= presentation.title %></h4>

  <p>
    <strong>Course:</strong>
    <%= presentation.course.name %>
  </p>

    <p>
      <strong>Due Date:</strong>
      <%= presentation.due_date %>
    </p>

    <p>
      <strong>Presenter(s):</strong>
      <% @authors.each do |author| %>
        <% if (presentation.id == author.presentation_id)%>
          <%= author.user.first + " " + author.user.last %>
        <% end %>
      <% end %>

    <% if current_user.role != "Student" or current_user.presentations.include?(@presentation)%>
      <p>
        <strong>Grade:</strong>
      <%= presentation.grade %>

      <% if current_user.role != "Student" %>
        <%= link_to 'Add/Edit Grade', edit_presentation_path(presentation) %>
      <% end %>
    </p>
    <% end %>

  </div>
</div>

app/views/presentations/edit.html.erb
<% provide(:title, "Editing...") %>
<h1>Editing presentation</h1>

<%= render "form", presentation: @presentation %>

<br>

<div>
  <%= link_to "Show this presentation", @presentation %> |
  <%= link_to "Back to presentations", presentations_path %>
</div>

app/views/presentations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Presentations</h1>

<% if user_signed_in? %>

<% if current_user.role == 'Instructor' or current_user.role == 'TA'%>
    <%= link_to "New presentation", new_presentation_path, class: "presentations-edit-button presentation-button" %>
    <br>
  <% end %>
  
  <div id="presentations">
    <% if @presentations.empty? %>
      <h4 class="presentation-container">There are no presentations scheduled.</h4>
    <% else %>
      <%if current_user.role == "Student"%>
        <h3 class="bold"><%= current_user.first %>'s Upcoming Presentations:</h3>
        <% if @user_presentations.empty? %>
          <h4 class="presentation-container">You have no presentations scheduled.</h4>
        <% else %>
          <% @user_presentations.each do |presentation| %>
            <div class="d-flex align-items-center">
              <div class="col-md-10">
                <%= render presentation %>
              </div>

              <div class="col-md-2">
                <%= link_to 'View Presentation', presentation_path(presentation), class: "presentation-button view-presentation-button" %>
              </div>
            </div>
            <br>
          <% end %>
        <% end %>

      <hr>
      <% end %>

      <h3 class="bold">Upcoming Course Presentations:</h3>
      <% if @other_presentations.empty? %>
        <h4 class="presentation-container">There are no other presentations scheduled.</h4>
      <% else %>
        <% @other_presentations.each do |presentation| %>
          <div class="d-flex align-items-center">
            <div class="col-md-10">
              <%= render presentation %>
            </div>

            <div class="col-md-2 d-flex flex-col gap-3">
              <%= link_to 'View Presentation', presentation_path(presentation), class: "presentation-button view-presentation-button" %>
              <% if current_user.role == "Student" %>
                <%= link_to 'Evaluate', new_evaluation_path(presentation_id: presentation.id), class: "presentation-button new-evaluation-button" %>
              <% end %>
            </div>
          </div>
          <br>
        <% end %>
      <% end %>
    <% end %>

    <hr>
  </div>

  <%= link_to "Back to Home", home_path, class: "presentations-back-button presentation-button" %>

<% else %>
  <p>Please <%= link_to 'sign in', new_user_session_path %> or <%= link_to 'sign up', new_user_registration_path %> to see all upcoming presentations.</p>
<% end %>

app/views/presentations/new.html.erb
<% provide(:title, "New Presentation") %>
<h1>New presentation</h1>

<%= render "form", presentation: @presentation %>

<br>

<div>
  <%= link_to "Back to presentations", presentations_path %>
</div>

app/views/presentations/show.html.erb
<p style="color: green"><%= notice %></p>


<h3 class="bold">Presentation:</h3>
<%= render @presentation %>
<br>

<div class="d-flex gap-3">
  <%= link_to "Back to presentations", presentations_path, class: "presentations-back-button presentation-button" %>

  <% if current_user.role != 'Student' %>
    <%= link_to "Edit this presentation", edit_presentation_path(@presentation), class: "presentations-edit-button presentation-button" %>
    <%= button_to "Destroy this presentation", @presentation, method: :delete, class: "presentations-delete-button presentation-button"%>
    <%= link_to 'View Evaluations', presentation_evaluations_path(@presentation), class: "presentation-button view-presentation-button" %>
  <% elsif Author.where(user_id: current_user.id, presentation_id: @presentation.id).exists? %>
    <%= link_to 'View Evaluations', presentation_evaluations_path(@presentation), class: "presentation-button view-presentation-button" %>
  <% else %>
    <%= link_to 'Evaluate', new_evaluation_path(presentation_id: @presentation.id), class: "presentation-button new-evaluation-button" %>
  <%end%>
</div>

<hr>

<% if current_user.role != "Student" or Author.where(user_id: current_user.id, presentation_id: @presentation.id).exists? %>
  <h3 class="bold">Evaluation Averages:</h3>

  <% if @evaluations.blank? %>
    <h4 class="presentation-container">There are no evaluations for this presentation.</h4>
  <% else %>
    <% @attribute_averages.each do |presentation, averages| %>
      <div class= "display_stats">
        <h4>Number of Evaluations: <%= averages['evaluation_count'] %> / <%=@student_count%> </h4>

        <div class="stats-grid">
          <h4 class="bold stats-grid-title">Quality</h4>
          <h4 class="bold stats-grid-title">Average Score (0-5)</h4>

          <% averages.each do |attribute, average| %>
            <% if attribute.humanize == "Evaluation count" %>
              <% next %>
            <% end %>
            <p class="stats-item stats-attr"><%= @attribute_labels[attribute] %></p>
            <p class="stats-item stats-score"><%= number_with_precision(average, precision: 2) %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>