config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :authors
      resources :courses
      resources :evaluations
      resources :presentations
      resources :users

      root to: "authors#index"
  end

  resources :courses
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  resources :presentations do
    resources :evaluations
  end
  resources :authors
  resources :evaluations
  
  devise_for :users, controllers: {
  registrations: 'users/registrations'
}

  resources :users do
    member do
      put 'change_role'
    end
    collection do
      get 'new_user'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"

  # define other roots
  get 'home', to: 'static_pages#home', as: 'home'
  get 'help', to: 'static_pages#help', as: 'help'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'presentations', to: 'presentations#index', as: 'presentations_path'
  get 'evaluations', to: 'evaluations#index', as: 'evaluations_path'
  get 'users', to: 'users#index', as: 'users_path'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable #, :recoverable

  has_many :evaluations, dependent: :destroy
  has_many :authors, dependent: :destroy
  has_many :presentations, through: :authors
  belongs_to :course
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    before_action :configure_account_update_params, only: [:update]


  def new
    # Get the parameter from the URL
    @role = params[:role] || "Student"
  
    if params[:course]
      @course = Course.find(params[:course])
    end

    # Call the Devise registrations controller
    super
  end

  def create
    super do |resource|
      # If the form submission fails, retain the parameters
      if resource.errors.any?
        resource.email = params[:user][:email]
        resource.course_id = params[:user][:course_id]
        resource.role = params[:user][:role]
      end
    end
  end

  
  private

  def configure_sign_up_params
    # Permit additional parameters to be passed during registration
    devise_parameter_sanitizer.permit(:sign_up, keys: [:your_parameter])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :current_password, :course_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted.'
  end

  def change_role
    @user = User.find(params[:id])
    if @user.role == 'TA'
      @user.update(role: 'Student')
    else
      @user.update(role: 'TA')
    end
    redirect_to users_path, notice: 'User role changed successfully.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :first, :last, :password, :course_id, :role)
  end

end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/users/index.html.erb
<% provide(:title, "Users") %>
<h1>Course Roster</h1>
<h3 class="bold"><%= current_user.course.name %></h3>

<table class= "display_table">
  <thead>
    <tr>
      <th>Email</th>
      <th>First</th>
      <th>Last</th>
      <th>Course</th>
      <th>Role</th>
      <% if current_user.role == "Instructor" %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <% if user.course == current_user.course%>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.first %></td>
          <td><%= user.last %></td>
          <td><%= user.course.name %></td>
          
          <td><%= user.role %></td>
          
            <% if (current_user.role != "Instructor" and user == current_user) or current_user.role == "Instructor"%>
            <td>
              <%= link_to 'Show', user %>
            </td>
            <% end%>
          
          <%if current_user.role == "Instructor" and user != current_user%>
            <td><%= button_to 'Create/Demote TA', change_role_user_path(user), method: :put %></td>
            <td><%= button_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%elsif current_user.role == "Instructor"%>
            <td>Update Student Roles</td>
            <td>Unenroll Students</td>
          <%end%>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to "Back to Home Page", root_path, class: "presentations-back-button presentation-button" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "form-options">
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First:</strong>
  <%= @user.first %>
</p>

<p>
  <strong>Last:</strong>
  <%= @user.last %>
</p>

<p>
  <strong>Courses:</strong>
  <%= @user.course.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>
</div>

<%= link_to 'Back', users_path %>