config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :authors
      resources :courses
      resources :evaluations
      resources :presentations
      resources :users

      root to: "authors#index"
  end

  resources :courses
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  resources :presentations do
    resources :evaluations
  end
  resources :authors
  resources :evaluations
  
  devise_for :users, controllers: {
  registrations: 'users/registrations'
}

  resources :users do
    member do
      put 'change_role'
    end
    collection do
      get 'new_user'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"

  # define other roots
  get 'home', to: 'static_pages#home', as: 'home'
  get 'help', to: 'static_pages#help', as: 'help'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'presentations', to: 'presentations#index', as: 'presentations_path'
  get 'evaluations', to: 'evaluations#index', as: 'evaluations_path'
  get 'users', to: 'users#index', as: 'users_path'

end

app/views/layouts/_footer.html.erb
<footer class="container">
  <small>
    Comprehensive Assessment of Presentation Effectiveness
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", home_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse" id="mainnav">
  <div class="container">
    <%= link_to "CAPE", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <%if !user_signed_in?%>
            <li><%= link_to "Home", root_path %></li>
          <%end%>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if user_signed_in? %>
            <li id="sign-out-button"><%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-sm btn-primary"%></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </nav>
  </div>
</header>

<%if user_signed_in?%>
<header class="navbar navbar-inverse" id="subnav">
  <div class="container">
    <nav>
        <ul class="nav navbar-nav navbar-right">
          <%if current_user.role != "Admin"%>
            <li><%= link_to 'Home', root_path, class: 'bold' %></li>
            <li><%= link_to 'Presentations', presentations_path, class: 'bold' %></li>
            <li><%= link_to 'Evaluations', evaluations_path, class: 'bold' %></li>
            <li><%= link_to 'Roster', users_path, class: 'bold' %></li>
          <%else%>
            <li><%= link_to 'Admin Dashboard', admin_root_path, class: 'bold'%></li>
            <li><%= link_to 'Home', root_path, class: 'bold' %></li>
          <%end%>
        </ul>
      </nav>
  </div>
</header>
<% end %>

<% if notice != nil%>

<% elsif alert != nil%>
  <span class= "alert"><%= alert %></span>
<% else %>
  
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <title><%= yield(:title) %> | CAPE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div id="main" class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>

</html>